<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CountriesNationalitiesSeeder extends Seeder
{
    public function run()
    {
        // Get status ID for active status (assuming status ID 1 is active)
        $activeStatus = $this->db->table('status')->where('name', 'Active')->get()->getRow();
        $statusId = $activeStatus ? $activeStatus->id : 1;

        $countries = [
            ['name' => 'Afghanistan', 'country_code' => 'AFG', 'description' => 'Islamic Emirate of Afghanistan'],
            ['name' => 'Albania', 'country_code' => 'ALB', 'description' => 'Republic of Albania'],
            ['name' => 'Algeria', 'country_code' => 'DZA', 'description' => 'People\'s Democratic Republic of Algeria'],
            ['name' => 'American Samoa', 'country_code' => 'ASM', 'description' => 'Territory of American Samoa'],
            ['name' => 'Andorra', 'country_code' => 'AND', 'description' => 'Principality of Andorra'],
            ['name' => 'Angola', 'country_code' => 'AGO', 'description' => 'Republic of Angola'],
            ['name' => 'Anguilla', 'country_code' => 'AIA', 'description' => 'Anguilla'],
            ['name' => 'Antarctica', 'country_code' => 'ATA', 'description' => 'Antarctica'],
            ['name' => 'Antigua and Barbuda', 'country_code' => 'ATG', 'description' => 'Antigua and Barbuda'],
            ['name' => 'Argentina', 'country_code' => 'ARG', 'description' => 'Argentine Republic'],
            ['name' => 'Armenia', 'country_code' => 'ARM', 'description' => 'Republic of Armenia'],
            ['name' => 'Aruba', 'country_code' => 'ABW', 'description' => 'Aruba'],
            ['name' => 'Australia', 'country_code' => 'AUS', 'description' => 'Commonwealth of Australia'],
            ['name' => 'Austria', 'country_code' => 'AUT', 'description' => 'Republic of Austria'],
            ['name' => 'Azerbaijan', 'country_code' => 'AZE', 'description' => 'Republic of Azerbaijan'],
            ['name' => 'Bahamas', 'country_code' => 'BHS', 'description' => 'Commonwealth of the Bahamas'],
            ['name' => 'Bahrain', 'country_code' => 'BHR', 'description' => 'Kingdom of Bahrain'],
            ['name' => 'Bangladesh', 'country_code' => 'BGD', 'description' => 'People\'s Republic of Bangladesh'],
            ['name' => 'Barbados', 'country_code' => 'BRB', 'description' => 'Barbados'],
            ['name' => 'Belarus', 'country_code' => 'BLR', 'description' => 'Republic of Belarus'],
            ['name' => 'Belgium', 'country_code' => 'BEL', 'description' => 'Kingdom of Belgium'],
            ['name' => 'Belize', 'country_code' => 'BLZ', 'description' => 'Belize'],
            ['name' => 'Benin', 'country_code' => 'BEN', 'description' => 'Republic of Benin'],
            ['name' => 'Bermuda', 'country_code' => 'BMU', 'description' => 'Bermuda'],
            ['name' => 'Bhutan', 'country_code' => 'BTN', 'description' => 'Kingdom of Bhutan'],
            ['name' => 'Bolivia', 'country_code' => 'BOL', 'description' => 'Plurinational State of Bolivia'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'country_code' => 'BES', 'description' => 'Bonaire, Sint Eustatius and Saba'],
            ['name' => 'Bosnia and Herzegovina', 'country_code' => 'BIH', 'description' => 'Bosnia and Herzegovina'],
            ['name' => 'Botswana', 'country_code' => 'BWA', 'description' => 'Republic of Botswana'],
            ['name' => 'Bouvet Island', 'country_code' => 'BVT', 'description' => 'Bouvet Island'],
            ['name' => 'Brazil', 'country_code' => 'BRA', 'description' => 'Federative Republic of Brazil'],
            ['name' => 'British Indian Ocean Territory', 'country_code' => 'IOT', 'description' => 'British Indian Ocean Territory'],
            ['name' => 'Brunei Darussalam', 'country_code' => 'BRN', 'description' => 'Nation of Brunei, the Abode of Peace'],
            ['name' => 'Bulgaria', 'country_code' => 'BGR', 'description' => 'Republic of Bulgaria'],
            ['name' => 'Burkina Faso', 'country_code' => 'BFA', 'description' => 'Burkina Faso'],
            ['name' => 'Burundi', 'country_code' => 'BDI', 'description' => 'Republic of Burundi'],
            ['name' => 'Cabo Verde', 'country_code' => 'CPV', 'description' => 'Republic of Cabo Verde'],
            ['name' => 'Cambodia', 'country_code' => 'KHM', 'description' => 'Kingdom of Cambodia'],
            ['name' => 'Cameroon', 'country_code' => 'CMR', 'description' => 'Republic of Cameroon'],
            ['name' => 'Canada', 'country_code' => 'CAN', 'description' => 'Canada'],
            ['name' => 'Cayman Islands', 'country_code' => 'CYM', 'description' => 'Cayman Islands'],
            ['name' => 'Central African Republic', 'country_code' => 'CAF', 'description' => 'Central African Republic'],
            ['name' => 'Chad', 'country_code' => 'TCD', 'description' => 'Republic of Chad'],
            ['name' => 'Chile', 'country_code' => 'CHL', 'description' => 'Republic of Chile'],
            ['name' => 'China', 'country_code' => 'CHN', 'description' => 'People\'s Republic of China'],
            ['name' => 'Christmas Island', 'country_code' => 'CXR', 'description' => 'Territory of Christmas Island'],
            ['name' => 'Cocos (Keeling) Islands', 'country_code' => 'CCK', 'description' => 'Territory of Cocos (Keeling) Islands'],
            ['name' => 'Colombia', 'country_code' => 'COL', 'description' => 'Republic of Colombia'],
            ['name' => 'Comoros', 'country_code' => 'COM', 'description' => 'Union of the Comoros'],
            ['name' => 'Congo', 'country_code' => 'COG', 'description' => 'Republic of the Congo'],
            ['name' => 'Congo, Democratic Republic of the', 'country_code' => 'COD', 'description' => 'Democratic Republic of the Congo'],
            ['name' => 'Cook Islands', 'country_code' => 'COK', 'description' => 'Cook Islands'],
            ['name' => 'Costa Rica', 'country_code' => 'CRI', 'description' => 'Republic of Costa Rica'],
            ['name' => 'Croatia', 'country_code' => 'HRV', 'description' => 'Republic of Croatia'],
            ['name' => 'Cuba', 'country_code' => 'CUB', 'description' => 'Republic of Cuba'],
            ['name' => 'Curaçao', 'country_code' => 'CUW', 'description' => 'Country of Curaçao'],
            ['name' => 'Cyprus', 'country_code' => 'CYP', 'description' => 'Republic of Cyprus'],
            ['name' => 'Czechia', 'country_code' => 'CZE', 'description' => 'Czech Republic'],
            ['name' => 'Côte d\'Ivoire', 'country_code' => 'CIV', 'description' => 'Republic of Côte d\'Ivoire'],
            ['name' => 'Denmark', 'country_code' => 'DNK', 'description' => 'Kingdom of Denmark'],
            ['name' => 'Djibouti', 'country_code' => 'DJI', 'description' => 'Republic of Djibouti'],
            ['name' => 'Dominica', 'country_code' => 'DMA', 'description' => 'Commonwealth of Dominica'],
            ['name' => 'Dominican Republic', 'country_code' => 'DOM', 'description' => 'Dominican Republic'],
            ['name' => 'Ecuador', 'country_code' => 'ECU', 'description' => 'Republic of Ecuador'],
            ['name' => 'Egypt', 'country_code' => 'EGY', 'description' => 'Arab Republic of Egypt'],
            ['name' => 'El Salvador', 'country_code' => 'SLV', 'description' => 'Republic of El Salvador'],
            ['name' => 'Equatorial Guinea', 'country_code' => 'GNQ', 'description' => 'Republic of Equatorial Guinea'],
            ['name' => 'Eritrea', 'country_code' => 'ERI', 'description' => 'State of Eritrea'],
            ['name' => 'Estonia', 'country_code' => 'EST', 'description' => 'Republic of Estonia'],
            ['name' => 'Eswatini', 'country_code' => 'SWZ', 'description' => 'Kingdom of Eswatini'],
            ['name' => 'Ethiopia', 'country_code' => 'ETH', 'description' => 'Federal Democratic Republic of Ethiopia'],
            ['name' => 'Falkland Islands (Malvinas)', 'country_code' => 'FLK', 'description' => 'Falkland Islands'],
            ['name' => 'Faroe Islands', 'country_code' => 'FRO', 'description' => 'Faroe Islands'],
            ['name' => 'Fiji', 'country_code' => 'FJI', 'description' => 'Republic of Fiji'],
            ['name' => 'Finland', 'country_code' => 'FIN', 'description' => 'Republic of Finland'],
            ['name' => 'France', 'country_code' => 'FRA', 'description' => 'French Republic'],
            ['name' => 'French Guiana', 'country_code' => 'GUF', 'description' => 'Guiana'],
            ['name' => 'French Polynesia', 'country_code' => 'PYF', 'description' => 'French Polynesia'],
            ['name' => 'French Southern Territories', 'country_code' => 'ATF', 'description' => 'French Southern and Antarctic Lands'],
            ['name' => 'Gabon', 'country_code' => 'GAB', 'description' => 'Gabonese Republic'],
            ['name' => 'Gambia', 'country_code' => 'GMB', 'description' => 'Republic of the Gambia'],
            ['name' => 'Georgia', 'country_code' => 'GEO', 'description' => 'Georgia'],
            ['name' => 'Germany', 'country_code' => 'DEU', 'description' => 'Federal Republic of Germany'],
            ['name' => 'Ghana', 'country_code' => 'GHA', 'description' => 'Republic of Ghana'],
            ['name' => 'Gibraltar', 'country_code' => 'GIB', 'description' => 'Gibraltar'],
            ['name' => 'Greece', 'country_code' => 'GRC', 'description' => 'Hellenic Republic'],
            ['name' => 'Greenland', 'country_code' => 'GRL', 'description' => 'Greenland'],
            ['name' => 'Grenada', 'country_code' => 'GRD', 'description' => 'Grenada'],
            ['name' => 'Guadeloupe', 'country_code' => 'GLP', 'description' => 'Guadeloupe'],
            ['name' => 'Guam', 'country_code' => 'GUM', 'description' => 'Territory of Guam'],
            ['name' => 'Guatemala', 'country_code' => 'GTM', 'description' => 'Republic of Guatemala'],
            ['name' => 'Guernsey', 'country_code' => 'GGY', 'description' => 'Bailiwick of Guernsey'],
            ['name' => 'Guinea', 'country_code' => 'GIN', 'description' => 'Republic of Guinea'],
            ['name' => 'Guinea-Bissau', 'country_code' => 'GNB', 'description' => 'Republic of Guinea-Bissau'],
            ['name' => 'Guyana', 'country_code' => 'GUY', 'description' => 'Co-operative Republic of Guyana'],
            ['name' => 'Haiti', 'country_code' => 'HTI', 'description' => 'Republic of Haiti'],
            ['name' => 'Heard Island and McDonald Islands', 'country_code' => 'HMD', 'description' => 'Territory of Heard Island and McDonald Islands'],
            ['name' => 'Holy See (Vatican City State)', 'country_code' => 'VAT', 'description' => 'Vatican City State'],
            ['name' => 'Honduras', 'country_code' => 'HND', 'description' => 'Republic of Honduras'],
            ['name' => 'Hong Kong', 'country_code' => 'HKG', 'description' => 'Hong Kong Special Administrative Region of China'],
            ['name' => 'Hungary', 'country_code' => 'HUN', 'description' => 'Hungary'],
            ['name' => 'Iceland', 'country_code' => 'ISL', 'description' => 'Republic of Iceland'],
            ['name' => 'India', 'country_code' => 'IND', 'description' => 'Republic of India'],
            ['name' => 'Indonesia', 'country_code' => 'IDN', 'description' => 'Republic of Indonesia'],
            ['name' => 'Iran, Islamic Republic of', 'country_code' => 'IRN', 'description' => 'Islamic Republic of Iran'],
            ['name' => 'Iraq', 'country_code' => 'IRQ', 'description' => 'Republic of Iraq'],
            ['name' => 'Ireland', 'country_code' => 'IRL', 'description' => 'Ireland'],
            ['name' => 'Isle of Man', 'country_code' => 'IMN', 'description' => 'Isle of Man'],
            ['name' => 'Israel', 'country_code' => 'ISR', 'description' => 'State of Israel'],
            ['name' => 'Italy', 'country_code' => 'ITA', 'description' => 'Italian Republic'],
            ['name' => 'Jamaica', 'country_code' => 'JAM', 'description' => 'Jamaica'],
            ['name' => 'Japan', 'country_code' => 'JPN', 'description' => 'Japan'],
            ['name' => 'Jersey', 'country_code' => 'JEY', 'description' => 'Bailiwick of Jersey'],
            ['name' => 'Jordan', 'country_code' => 'JOR', 'description' => 'Hashemite Kingdom of Jordan'],
            ['name' => 'Kazakhstan', 'country_code' => 'KAZ', 'description' => 'Republic of Kazakhstan'],
            ['name' => 'Kenya', 'country_code' => 'KEN', 'description' => 'Republic of Kenya'],
            ['name' => 'Kiribati', 'country_code' => 'KIR', 'description' => 'Republic of Kiribati'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'country_code' => 'PRK', 'description' => 'Democratic People\'s Republic of Korea'],
            ['name' => 'Korea, Republic of', 'country_code' => 'KOR', 'description' => 'Republic of Korea'],
            ['name' => 'Kuwait', 'country_code' => 'KWT', 'description' => 'State of Kuwait'],
            ['name' => 'Kyrgyzstan', 'country_code' => 'KGZ', 'description' => 'Kyrgyz Republic'],
            ['name' => 'Lao People\'s Democratic Republic', 'country_code' => 'LAO', 'description' => 'Lao People\'s Democratic Republic'],
            ['name' => 'Latvia', 'country_code' => 'LVA', 'description' => 'Republic of Latvia'],
            ['name' => 'Lebanon', 'country_code' => 'LBN', 'description' => 'Lebanese Republic'],
            ['name' => 'Lesotho', 'country_code' => 'LSO', 'description' => 'Kingdom of Lesotho'],
            ['name' => 'Liberia', 'country_code' => 'LBR', 'description' => 'Republic of Liberia'],
            ['name' => 'Libya', 'country_code' => 'LBY', 'description' => 'State of Libya'],
            ['name' => 'Liechtenstein', 'country_code' => 'LIE', 'description' => 'Principality of Liechtenstein'],
            ['name' => 'Lithuania', 'country_code' => 'LTU', 'description' => 'Republic of Lithuania'],
            ['name' => 'Luxembourg', 'country_code' => 'LUX', 'description' => 'Grand Duchy of Luxembourg'],
            ['name' => 'Macao', 'country_code' => 'MAC', 'description' => 'Macao Special Administrative Region of China'],
            ['name' => 'Madagascar', 'country_code' => 'MDG', 'description' => 'Republic of Madagascar'],
            ['name' => 'Malawi', 'country_code' => 'MWI', 'description' => 'Republic of Malawi'],
            ['name' => 'Malaysia', 'country_code' => 'MYS', 'description' => 'Malaysia'],
            ['name' => 'Maldives', 'country_code' => 'MDV', 'description' => 'Republic of Maldives'],
            ['name' => 'Mali', 'country_code' => 'MLI', 'description' => 'Republic of Mali'],
            ['name' => 'Malta', 'country_code' => 'MLT', 'description' => 'Republic of Malta'],
            ['name' => 'Marshall Islands', 'country_code' => 'MHL', 'description' => 'Republic of the Marshall Islands'],
            ['name' => 'Martinique', 'country_code' => 'MTQ', 'description' => 'Martinique'],
            ['name' => 'Mauritania', 'country_code' => 'MRT', 'description' => 'Islamic Republic of Mauritania'],
            ['name' => 'Mauritius', 'country_code' => 'MUS', 'description' => 'Republic of Mauritius'],
            ['name' => 'Mayotte', 'country_code' => 'MYT', 'description' => 'Department of Mayotte'],
            ['name' => 'Mexico', 'country_code' => 'MEX', 'description' => 'United Mexican States'],
            ['name' => 'Micronesia, Federated States of', 'country_code' => 'FSM', 'description' => 'Federated States of Micronesia'],
            ['name' => 'Moldova, Republic of', 'country_code' => 'MDA', 'description' => 'Republic of Moldova'],
            ['name' => 'Monaco', 'country_code' => 'MCO', 'description' => 'Principality of Monaco'],
            ['name' => 'Mongolia', 'country_code' => 'MNG', 'description' => 'Mongolia'],
            ['name' => 'Montenegro', 'country_code' => 'MNE', 'description' => 'Montenegro'],
            ['name' => 'Montserrat', 'country_code' => 'MSR', 'description' => 'Montserrat'],
            ['name' => 'Morocco', 'country_code' => 'MAR', 'description' => 'Kingdom of Morocco'],
            ['name' => 'Mozambique', 'country_code' => 'MOZ', 'description' => 'Republic of Mozambique'],
            ['name' => 'Myanmar', 'country_code' => 'MMR', 'description' => 'Republic of the Union of Myanmar'],
            ['name' => 'Namibia', 'country_code' => 'NAM', 'description' => 'Republic of Namibia'],
            ['name' => 'Nauru', 'country_code' => 'NRU', 'description' => 'Republic of Nauru'],
            ['name' => 'Nepal', 'country_code' => 'NPL', 'description' => 'Federal Democratic Republic of Nepal'],
            ['name' => 'Netherlands', 'country_code' => 'NLD', 'description' => 'Kingdom of the Netherlands'],
            ['name' => 'New Caledonia', 'country_code' => 'NCL', 'description' => 'New Caledonia'],
            ['name' => 'New Zealand', 'country_code' => 'NZL', 'description' => 'New Zealand'],
            ['name' => 'Nicaragua', 'country_code' => 'NIC', 'description' => 'Republic of Nicaragua'],
            ['name' => 'Niger', 'country_code' => 'NER', 'description' => 'Republic of the Niger'],
            ['name' => 'Nigeria', 'country_code' => 'NGA', 'description' => 'Federal Republic of Nigeria'],
            ['name' => 'Niue', 'country_code' => 'NIU', 'description' => 'Niue'],
            ['name' => 'Norfolk Island', 'country_code' => 'NFK', 'description' => 'Territory of Norfolk Island'],
            ['name' => 'North Macedonia', 'country_code' => 'MKD', 'description' => 'Republic of North Macedonia'],
            ['name' => 'Northern Mariana Islands', 'country_code' => 'MNP', 'description' => 'Commonwealth of the Northern Mariana Islands'],
            ['name' => 'Norway', 'country_code' => 'NOR', 'description' => 'Kingdom of Norway'],
            ['name' => 'Oman', 'country_code' => 'OMN', 'description' => 'Sultanate of Oman'],
            ['name' => 'Pakistan', 'country_code' => 'PAK', 'description' => 'Islamic Republic of Pakistan'],
            ['name' => 'Palau', 'country_code' => 'PLW', 'description' => 'Republic of Palau'],
            ['name' => 'Palestine, State of', 'country_code' => 'PSE', 'description' => 'State of Palestine'],
            ['name' => 'Panama', 'country_code' => 'PAN', 'description' => 'Republic of Panama'],
            ['name' => 'Papua New Guinea', 'country_code' => 'PNG', 'description' => 'Independent State of Papua New Guinea'],
            ['name' => 'Paraguay', 'country_code' => 'PRY', 'description' => 'Republic of Paraguay'],
            ['name' => 'Peru', 'country_code' => 'PER', 'description' => 'Republic of Peru'],
            ['name' => 'Philippines', 'country_code' => 'PHL', 'description' => 'Republic of the Philippines'],
            ['name' => 'Pitcairn', 'country_code' => 'PCN', 'description' => 'Pitcairn, Henderson, Ducie and Oeno Islands'],
            ['name' => 'Poland', 'country_code' => 'POL', 'description' => 'Republic of Poland'],
            ['name' => 'Portugal', 'country_code' => 'PRT', 'description' => 'Portuguese Republic'],
            ['name' => 'Puerto Rico', 'country_code' => 'PRI', 'description' => 'Commonwealth of Puerto Rico'],
            ['name' => 'Qatar', 'country_code' => 'QAT', 'description' => 'State of Qatar'],
            ['name' => 'Romania', 'country_code' => 'ROU', 'description' => 'Romania'],
            ['name' => 'Russian Federation', 'country_code' => 'RUS', 'description' => 'Russian Federation'],
            ['name' => 'Rwanda', 'country_code' => 'RWA', 'description' => 'Republic of Rwanda'],
            ['name' => 'Réunion', 'country_code' => 'REU', 'description' => 'Réunion'],
            ['name' => 'Saint Barthélemy', 'country_code' => 'BLM', 'description' => 'Collectivity of Saint Barthélemy'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'country_code' => 'SHN', 'description' => 'Saint Helena, Ascension and Tristan da Cunha'],
            ['name' => 'Saint Kitts and Nevis', 'country_code' => 'KNA', 'description' => 'Federation of Saint Christopher and Nevis'],
            ['name' => 'Saint Lucia', 'country_code' => 'LCA', 'description' => 'Saint Lucia'],
            ['name' => 'Saint Martin (French part)', 'country_code' => 'MAF', 'description' => 'Collectivity of Saint Martin'],
            ['name' => 'Saint Pierre and Miquelon', 'country_code' => 'SPM', 'description' => 'Territorial Collectivity of Saint Pierre and Miquelon'],
            ['name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VCT', 'description' => 'Saint Vincent and the Grenadines'],
            ['name' => 'Samoa', 'country_code' => 'WSM', 'description' => 'Independent State of Samoa'],
            ['name' => 'San Marino', 'country_code' => 'SMR', 'description' => 'Republic of San Marino'],
            ['name' => 'Sao Tome and Principe', 'country_code' => 'STP', 'description' => 'Democratic Republic of São Tomé and Príncipe'],
            ['name' => 'Saudi Arabia', 'country_code' => 'SAU', 'description' => 'Kingdom of Saudi Arabia'],
            ['name' => 'Senegal', 'country_code' => 'SEN', 'description' => 'Republic of Senegal'],
            ['name' => 'Serbia', 'country_code' => 'SRB', 'description' => 'Republic of Serbia'],
            ['name' => 'Seychelles', 'country_code' => 'SYC', 'description' => 'Republic of Seychelles'],
            ['name' => 'Sierra Leone', 'country_code' => 'SLE', 'description' => 'Republic of Sierra Leone'],
            ['name' => 'Singapore', 'country_code' => 'SGP', 'description' => 'Republic of Singapore'],
            ['name' => 'Sint Maarten (Dutch part)', 'country_code' => 'SXM', 'description' => 'Sint Maarten'],
            ['name' => 'Slovakia', 'country_code' => 'SVK', 'description' => 'Slovak Republic'],
            ['name' => 'Slovenia', 'country_code' => 'SVN', 'description' => 'Republic of Slovenia'],
            ['name' => 'Solomon Islands', 'country_code' => 'SLB', 'description' => 'Solomon Islands'],
            ['name' => 'Somalia', 'country_code' => 'SOM', 'description' => 'Federal Republic of Somalia'],
            ['name' => 'South Africa', 'country_code' => 'ZAF', 'description' => 'Republic of South Africa'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'country_code' => 'SGS', 'description' => 'South Georgia and the South Sandwich Islands'],
            ['name' => 'South Sudan', 'country_code' => 'SSD', 'description' => 'Republic of South Sudan'],
            ['name' => 'Spain', 'country_code' => 'ESP', 'description' => 'Kingdom of Spain'],
            ['name' => 'Sri Lanka', 'country_code' => 'LKA', 'description' => 'Democratic Socialist Republic of Sri Lanka'],
            ['name' => 'Sudan', 'country_code' => 'SDN', 'description' => 'Republic of the Sudan'],
            ['name' => 'Suriname', 'country_code' => 'SUR', 'description' => 'Republic of Suriname'],
            ['name' => 'Svalbard and Jan Mayen', 'country_code' => 'SJM', 'description' => 'Svalbard and Jan Mayen'],
            ['name' => 'Sweden', 'country_code' => 'SWE', 'description' => 'Kingdom of Sweden'],
            ['name' => 'Switzerland', 'country_code' => 'CHE', 'description' => 'Swiss Confederation'],
            ['name' => 'Syrian Arab Republic', 'country_code' => 'SYR', 'description' => 'Syrian Arab Republic'],
            ['name' => 'Taiwan, Province of China', 'country_code' => 'TWN', 'description' => 'Taiwan'],
            ['name' => 'Tajikistan', 'country_code' => 'TJK', 'description' => 'Republic of Tajikistan'],
            ['name' => 'Tanzania, United Republic of', 'country_code' => 'TZA', 'description' => 'United Republic of Tanzania'],
            ['name' => 'Thailand', 'country_code' => 'THA', 'description' => 'Kingdom of Thailand'],
            ['name' => 'Timor-Leste', 'country_code' => 'TLS', 'description' => 'Democratic Republic of Timor-Leste'],
            ['name' => 'Togo', 'country_code' => 'TGO', 'description' => 'Togolese Republic'],
            ['name' => 'Tokelau', 'country_code' => 'TKL', 'description' => 'Tokelau'],
            ['name' => 'Tonga', 'country_code' => 'TON', 'description' => 'Kingdom of Tonga'],
            ['name' => 'Trinidad and Tobago', 'country_code' => 'TTO', 'description' => 'Republic of Trinidad and Tobago'],
            ['name' => 'Tunisia', 'country_code' => 'TUN', 'description' => 'Republic of Tunisia'],
            ['name' => 'Turkey', 'country_code' => 'TUR', 'description' => 'Republic of Turkey'],
            ['name' => 'Turkmenistan', 'country_code' => 'TKM', 'description' => 'Turkmenistan'],
            ['name' => 'Turks and Caicos Islands', 'country_code' => 'TCA', 'description' => 'Turks and Caicos Islands'],
            ['name' => 'Tuvalu', 'country_code' => 'TUV', 'description' => 'Tuvalu'],
            ['name' => 'Uganda', 'country_code' => 'UGA', 'description' => 'Republic of Uganda'],
            ['name' => 'Ukraine', 'country_code' => 'UKR', 'description' => 'Ukraine'],
            ['name' => 'United Arab Emirates', 'country_code' => 'ARE', 'description' => 'United Arab Emirates'],
            ['name' => 'United Kingdom of Great Britain and Northern Ireland', 'country_code' => 'GBR', 'description' => 'United Kingdom of Great Britain and Northern Ireland'],
            ['name' => 'United States of America', 'country_code' => 'USA', 'description' => 'United States of America'],
            ['name' => 'United States Minor Outlying Islands', 'country_code' => 'UMI', 'description' => 'United States Minor Outlying Islands'],
            ['name' => 'Uruguay', 'country_code' => 'URY', 'description' => 'Oriental Republic of Uruguay'],
            ['name' => 'Uzbekistan', 'country_code' => 'UZB', 'description' => 'Republic of Uzbekistan'],
            ['name' => 'Vanuatu', 'country_code' => 'VUT', 'description' => 'Republic of Vanuatu'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'country_code' => 'VEN', 'description' => 'Bolivarian Republic of Venezuela'],
            ['name' => 'Viet Nam', 'country_code' => 'VNM', 'description' => 'Socialist Republic of Viet Nam'],
            ['name' => 'Virgin Islands, British', 'country_code' => 'VGB', 'description' => 'Virgin Islands'],
            ['name' => 'Virgin Islands, U.S.', 'country_code' => 'VIR', 'description' => 'Virgin Islands of the United States'],
            ['name' => 'Wallis and Futuna', 'country_code' => 'WLF', 'description' => 'Territory of the Wallis and Futuna Islands'],
            ['name' => 'Western Sahara', 'country_code' => 'ESH', 'description' => 'Western Sahara'],
            ['name' => 'Yemen', 'country_code' => 'YEM', 'description' => 'Republic of Yemen'],
            ['name' => 'Zambia', 'country_code' => 'ZMB', 'description' => 'Republic of Zambia'],
            ['name' => 'Zimbabwe', 'country_code' => 'ZWE', 'description' => 'Republic of Zimbabwe'],
            ['name' => 'Åland Islands', 'country_code' => 'ALA', 'description' => 'Åland Islands']
        ];

        // Insert countries in batches to avoid memory issues
        $batchSize = 50;
        $totalCountries = count($countries);
        $inserted = 0;

        for ($i = 0; $i < $totalCountries; $i += $batchSize) {
            $batch = array_slice($countries, $i, $batchSize);
            $batchData = [];

            foreach ($batch as $country) {
                // Check if country already exists
                $existing = $this->db->table('nationalities')
                                    ->where('name', $country['name'])
                                    ->orWhere('country_code', $country['country_code'])
                                    ->get()
                                    ->getRow();

                if (!$existing) {
                    $batchData[] = [
                        'name' => $country['name'],
                        'country_code' => $country['country_code'],
                        'description' => $country['description'],
                        'status_id' => $statusId,
                        'created_by' => 1,
                        'created_at' => date('Y-m-d H:i:s')
                    ];
                    $inserted++;
                }
            }

            if (!empty($batchData)) {
                $this->db->table('nationalities')->insertBatch($batchData);
            }
        }

        echo "Successfully inserted {$inserted} countries into nationalities table.\n";
        echo "Skipped " . ($totalCountries - $inserted) . " countries that already existed.\n";
    }
}
